# --- Build Stage ---
FROM node:16 AS build

WORKDIR /frontend

# Install dependencies and build the app
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend ./
RUN npm run build --prod

# --- Runtime Stage with NGINX ---
FROM nginx:alpine AS final

# Copy the build output to NGINX directory
COPY --from=build ./frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
