# --- Development Stage ---
FROM node:18 AS dev

WORKDIR /frontend

# Copy source files
COPY ./frontend ./

# Install Angular CLI globally
RUN npm install -g @angular/cli@16

# Install dependencies
COPY ./frontend/package*.json ./
RUN npm install --legacy-peer-deps

EXPOSE 4200

CMD ["npm", "start"]
