# --- Base dependencies ---
FROM node:18 AS dev

WORKDIR /frontend

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Install dependencies
COPY ../frontend/package*.json ./
RUN npm install --force

# Copy source files
COPY ../frontend .

# Expose dev port
EXPOSE 4200

# Start dev server
CMD ["npm", "start"]
