services:
  frontend-stt:
    container_name: frontend-stt
    build:
      context: ../../
      dockerfile: docker/Dockerfiles/Dockerfile.frontend.dev
    ports:
      - "4222:4200"
    volumes:
      - ../../frontend:/frontend
    environment:
      - NODE_ENV=development
    command: npm start

  backend-stt:
    ports:
      - "3000:3000"
    volumes:
      - ../../backend:/backend
      - ../../engines/utils:/backend/utils
    command: npx nodemon server.js
