services:

  frontend-stt:
    container_name: frontend-stt
    image: frontend-stt:prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    command: [ "nginx", "-g", "daemon off;" ]

  backend-stt:
    container_name: backend-stt
    image: backend-stt:prod
    ports:
      - "3000:3000"
    command: node server.js
